VERSION 0.7
FROM node:18-bullseye
RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
    && echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list
# Install Chrome.
RUN apt-get update && apt-get -y install google-chrome-stable
WORKDIR /tests

deps:
    COPY package.json ./
    COPY package-lock.json ./
    RUN npm install

docker:
    ARG tag='latest'
    FROM +deps
    COPY src src
    COPY nightwatch.conf.js ./
    COPY tsconfig.json ./
    ENTRYPOINT ["npm", "run", "test"]
    SAVE IMAGE milestone-tracker-tests:$tag
