VERSION 0.7

deps:
    FROM node:18-bullseye
    WORKDIR /tests

    RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
        && echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list
    RUN apt-get update && apt-get -y install google-chrome-stable

    COPY package.json ./
    COPY package-lock.json ./

    RUN npm install

src:
    FROM +deps

    COPY src src
    COPY nightwatch.conf.js ./
    COPY tsconfig.json ./

docker:
    FROM +src

    ENTRYPOINT ["npm", "run", "test"]

# TODO: This is failing
# check:
#     FROM +src

#     RUN npm run test

# publish:
#     FROM +docker

#     ARG tag='latest'

#     SAVE IMAGE milestone-tracker-tests:$tag
