CREATE TABLE IF NOT EXISTS public.proposals
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    title character varying COLLATE pg_catalog."default",
    url character varying COLLATE pg_catalog."default",
    project_id bigint,
    completion_date timestamp without time zone,
    created_at timestamp with time zone DEFAULT now(),
    challenge_id bigint,
    budget bigint,
    milestones_qty bigint DEFAULT 5,
    funds_distributed bigint DEFAULT 0,
    CONSTRAINT proposals_pkey PRIMARY KEY (id),
    CONSTRAINT proposals_challenge_id_fkey FOREIGN KEY (challenge_id)
        REFERENCES public.challenges (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.proposals
    OWNER to postgres;

ALTER TABLE IF EXISTS public.proposals
    ENABLE ROW LEVEL SECURITY;

GRANT ALL ON TABLE public.proposals TO anon;

GRANT ALL ON TABLE public.proposals TO authenticated;

GRANT ALL ON TABLE public.proposals TO postgres;

GRANT ALL ON TABLE public.proposals TO service_role;
CREATE POLICY public
    ON public.proposals
    AS PERMISSIVE
    FOR SELECT
    TO public
    USING (true);