CREATE TABLE IF NOT EXISTS public.funds
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    title character varying COLLATE pg_catalog."default",
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT funds_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.funds
    OWNER to postgres;

ALTER TABLE IF EXISTS public.funds
    ENABLE ROW LEVEL SECURITY;

GRANT ALL ON TABLE public.funds TO anon;

GRANT ALL ON TABLE public.funds TO authenticated;

GRANT ALL ON TABLE public.funds TO postgres;

GRANT ALL ON TABLE public.funds TO service_role;
CREATE POLICY "Public select"
    ON public.funds
    AS PERMISSIVE
    FOR SELECT
    TO public
    USING (true);