CREATE TABLE IF NOT EXISTS public.allocations
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    proposal_id bigint,
    user_id uuid,
    user_idd bigint,
    CONSTRAINT allocations_pkey PRIMARY KEY (id),
    CONSTRAINT allocations_proposal_id_fkey FOREIGN KEY (proposal_id)
        REFERENCES public.proposals (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT allocations_user_id_fkey FOREIGN KEY (user_id)
        REFERENCES auth.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT allocations_user_idd_fkey FOREIGN KEY (user_idd)
        REFERENCES public.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.allocations
    OWNER to postgres;

ALTER TABLE IF EXISTS public.allocations
    ENABLE ROW LEVEL SECURITY;

GRANT ALL ON TABLE public.allocations TO authenticated;

GRANT ALL ON TABLE public.allocations TO anon;

GRANT ALL ON TABLE public.allocations TO service_role;

GRANT ALL ON TABLE public.allocations TO postgres;
CREATE POLICY "Allocations delete"
    ON public.allocations
    AS PERMISSIVE
    FOR DELETE
    TO public
    USING (can_access_users(auth.uid()));
CREATE POLICY "Allocations insert"
    ON public.allocations
    AS PERMISSIVE
    FOR INSERT
    TO public
    WITH CHECK (can_access_users(auth.uid()));
CREATE POLICY "Allocations select"
    ON public.allocations
    AS PERMISSIVE
    FOR SELECT
    TO public
    USING (true);