CREATE TABLE IF NOT EXISTS public.challenges
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    title character varying COLLATE pg_catalog."default",
    created_at timestamp with time zone DEFAULT now(),
    fund_id bigint,
    CONSTRAINT challenges_pkey PRIMARY KEY (id),
    CONSTRAINT challenges_fund_id_fkey FOREIGN KEY (fund_id)
        REFERENCES public.funds (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.challenges
    OWNER to postgres;

ALTER TABLE IF EXISTS public.challenges
    ENABLE ROW LEVEL SECURITY;

GRANT ALL ON TABLE public.challenges TO anon;

GRANT ALL ON TABLE public.challenges TO authenticated;

GRANT ALL ON TABLE public.challenges TO postgres;

GRANT ALL ON TABLE public.challenges TO service_role;
CREATE POLICY "Public visible"
    ON public.challenges
    AS PERMISSIVE
    FOR SELECT
    TO public
    USING (true);