VERSION 0.7
FROM node:16-alpine3.17
WORKDIR /frontend

deps:
    COPY package.json ./
    COPY package-lock.json ./
    RUN npm install

build:
    FROM +deps
    COPY src src
    COPY public public
    COPY index.html ./
    COPY vite.config.js ./
    COPY .eslintrc.js ./
    COPY .env.example .env
    RUN mkdir -p ./dist
    RUN npm run build
    SAVE ARTIFACT dist /dist AS LOCAL dist

docker:
    ARG tag='latest'
    FROM +deps
    FROM nginx:stable-alpine3.17
    RUN apk update && apk add bash
    COPY +build/dist /app
    COPY ./nginx.conf /etc/nginx/nginx.conf
    COPY ./entry.sh /docker-entrypoint.d/50-set-frontend-env.sh
    EXPOSE 80
    
    SAVE IMAGE milestone-module-frontend:$tag