VERSION 0.7
FROM node:16-alpine3.17
WORKDIR /frontend

deps:
    COPY package.json ./
    COPY package-lock.json ./
    RUN npm install

build:
    FROM +deps
    COPY src src
    COPY index.html ./
    COPY vite.config.js ./
    COPY .eslintrc.js ./
    COPY .env.example .env
    RUN mkdir -p ./dist
    RUN npm run build
    SAVE ARTIFACT dist /dist AS LOCAL dist

set-env:
    FROM +build
    RUN npx vue-inject-env set
    SAVE ARTIFACT dist /dist AS LOCAL dist

docker:
    ARG tag='latest'
    FROM +deps
    FROM nginx:stable-alpine3.17
    COPY +set-env/dist /app
    COPY ./nginx.conf /etc/nginx/nginx.conf
    EXPOSE 80
    SAVE IMAGE milestone-module-frontend:$tag