VERSION 0.7

deps:
    FROM node:16-alpine3.17
    WORKDIR /frontend

    COPY package.json ./
    COPY package-lock.json ./

    RUN npm install

src:
    FROM +deps

    COPY src src
    COPY public public
    COPY index.html ./
    COPY vite.config.js ./
    COPY .eslintrc.js ./
    COPY .env.example .env

build:
    FROM +src

    RUN mkdir -p ./dist
    RUN npm run build

    SAVE ARTIFACT dist /dist AS LOCAL dist

docker:
    FROM +deps
    FROM nginx:stable-alpine3.17

    RUN apk update && apk add bash

    COPY +build/dist /app
    COPY ./nginx.conf /etc/nginx/nginx.conf
    COPY ./entry.sh /docker-entrypoint.d/50-set-frontend-env.sh

    EXPOSE 80

publish:
    FROM +docker

    ARG tag='latest'

    SAVE IMAGE milestone-module-frontend:$tag